[tool.mypy]
python_version = "3.11"
show_error_codes = true
check_untyped_defs = true
warn_unused_configs = true
ignore_missing_imports = true

[tool.black]
skip-string-normalization = true

[tool.flake8]
show-source = true
max-line-length = 99
application-import-names = "wazo_agid"
ignore = [
  "E203", # whitespace before ':'
  "W503", # line break before binary operator
]
exclude = [
    ".tox",
    ".eggs",
]

[tool.isort]
py_version = 311
profile = "black"
