# Copyright 2006-2024 The Wazo Authors  (see the AUTHORS file)
# SPDX-License-Identifier: GPL-3.0-or-later

BASE_CONTEXT = 'WAZO_BASE_CONTEXT'
CALL_OPTIONS = 'WAZO_CALLOPTIONS'
CALL_ORIGIN = 'WAZO_CALLORIGIN'
# ID of the callee
SRCNUM = 'WAZO_SRCNUM'
DESTINATION_ID = 'WAZO_DSTID'
DESTINATION_NUMBER = 'WAZO_DSTNUM'
HANGUP_RING_TIME = 'XIVO_HANGUPRINGTIME'
DESTINATION_EXTENSION_ID = 'WAZO_DST_EXTEN_ID'
INTERFACE = 'WAZO_INTERFACE'
OUTGOING_CALLER_ID_FORMAT = 'WAZO_OUTGOING_CALLER_ID_FORMAT'
OUTCALL_ID = 'XIVO_OUTCALLID'
OUTCALL_PREPROCESS_SUBROUTINE = 'XIVO_OUTCALLPREPROCESS_SUBROUTINE'
PATH = 'XIVO_PATH'
PATH_ID = 'XIVO_PATH_ID'
SELECTED_CALLER_ID = 'WAZO_SELECTED_CALLER_ID'
SOURCE_NUMBER = 'WAZO_SRCNUM'
TENANT_UUID = 'WAZO_TENANT_UUID'
TRUNK_EXTEN = 'XIVO_TRUNKEXTEN'
TRUNK_SUFFIX = 'XIVO_TRUNKSUFFIX'
FWD_REFERER = 'WAZO_FWD_REFERER'
# ID of the caller
USERID = 'WAZO_USERID'
USERUUID = 'WAZO_USERUUID'
USER_MOH = 'WAZO_USER_MOH_UUID'
