# Copyright 2006-2022 The Wazo Authors  (see the AUTHORS file)
# SPDX-License-Identifier: GPL-3.0-or-later

BASE_CONTEXT = 'XIVO_BASE_CONTEXT'
CALL_OPTIONS = 'XIVO_CALLOPTIONS'
CALL_ORIGIN = 'XIVO_CALLORIGIN'
# ID of the callee
SRCNUM = 'XIVO_SRCNUM'
DESTINATION_ID = 'XIVO_DSTID'
DESTINATION_NUMBER = 'XIVO_DSTNUM'
HANGUP_RING_TIME = 'XIVO_HANGUPRINGTIME'
DESTINATION_EXTENSION_ID = 'XIVO_DST_EXTEN_ID'
INTERFACE = 'XIVO_INTERFACE'
OUTCALL_ID = 'XIVO_OUTCALLID'
OUTCALL_PREPROCESS_SUBROUTINE = 'XIVO_OUTCALLPREPROCESS_SUBROUTINE'
PATH = 'XIVO_PATH'
PATH_ID = 'XIVO_PATH_ID'
SOURCE_NUMBER = 'XIVO_SRCNUM'
TENANT_UUID = 'WAZO_TENANT_UUID'
TRUNK_EXTEN = 'XIVO_TRUNKEXTEN'
TRUNK_SUFFIX = 'XIVO_TRUNKSUFFIX'
FWD_REFERER = 'XIVO_FWD_REFERER'
# ID of the caller
USERID = 'XIVO_USERID'
USERUUID = 'WAZO_USERUUID'
USER_MOH = 'WAZO_USER_MOH_UUID'
