# -*- coding: utf-8 -*-
# Copyright 2006-2017 The Wazo Authors  (see the AUTHORS file)
# SPDX-License-Identifier: GPL-3.0+

BASE_CONTEXT = 'XIVO_BASE_CONTEXT'
CALL_OPTIONS = 'XIVO_CALLOPTIONS'
CALL_ORIGIN = 'XIVO_CALLORIGIN'
CALL_RECORD_FILE_NAME = 'XIVO_CALLRECORDFILE'
# ID of the callee
SRCNUM = 'XIVO_SRCNUM'
DESTINATION_ID = 'XIVO_DSTID'
DESTINATION_NUMBER = 'XIVO_DSTNUM'
HANGUP_RING_TIME = 'XIVO_HANGUPRINGTIME'
DESTINATION_EXTENSION_ID = 'XIVO_DST_EXTEN_ID'
INTERFACE = 'XIVO_INTERFACE'
OUTCALL_ID = 'XIVO_OUTCALLID'
OUTCALL_PREPROCESS_SUBROUTINE = 'XIVO_OUTCALLPREPROCESS_SUBROUTINE'
PATH = 'XIVO_PATH'
PATH_ID = 'XIVO_PATH_ID'
SOURCE_NUMBER = 'XIVO_SRCNUM'
TRUNK_EXTEN = 'XIVO_TRUNKEXTEN'
TRUNK_SUFFIX = 'XIVO_TRUNKSUFFIX'
FWD_REFERER = 'XIVO_FWD_REFERER'
# ID of the caller
USERID = 'XIVO_USERID'
