services:
  sync:
    image: wazoplatform/wait
    environment:
      TIMEOUT: "${INTEGRATION_TEST_TIMEOUT}"

  agid:
    image: wazoplatform/wazo-agid-tests
    ports:
      - "4573"
    environment:
      - PYTHONUNBUFFERED=TRUE
    volumes:
      - "../..:/usr/src/wazo-agid"
      - "./etc/wazo-agid/conf.d/50-default.yml:/etc/wazo-agid/conf.d/50-default.yml"
      - "./etc/xivo/asterisk/xivo_in_callerid.conf:/etc/xivo/asterisk/xivo_in_callerid.conf"
      - "./etc/xivo/asterisk/xivo_ring.conf:/etc/xivo/asterisk/xivo_ring.conf"
      - "./etc/xivo/asterisk/xivo_fax.conf:/etc/xivo/asterisk/xivo_fax.conf"
      - "./etc/xivo/mail.txt:/etc/xivo/mail.txt"
      # - "${LOCAL_GIT_REPOS}/xivo-dao/xivo_dao:/opt/venv/lib/python3.11/site-packages/xivo_dao"
      # - "${LOCAL_GIT_REPOS}/xivo-lib-python/xivo:/opt/venv/lib/python3.11/site-packages/xivo"

  auth:
    image: wazoplatform/wazo-auth-mock
    ports:
      - '9497'

  calld:
    image: mockserver/mockserver
    environment:
      MOCKSERVER_SERVER_PORT: 9500
    ports:
      - "9500"

  confd:
    image: mockserver/mockserver
    environment:
      MOCKSERVER_SERVER_PORT: 9486
    ports:
      - "9486"

  agentd:
    image: mockserver/mockserver
    environment:
      MOCKSERVER_SERVER_PORT: 9493
    ports:
      - "9493"

  dird:
    image: mockserver/mockserver
    environment:
      MOCKSERVER_SERVER_PORT: 9489
    ports:
      - "9489"

  postgres:
    image: wazoplatform/wazo-confd-db-test:local
    ports:
      - "5432"
