FROM wazoplatform/wazo-agid

ENV PYTHONDONTWRITEBYTECODE='true'

COPY integration_tests/docker/mock_cmd.sh /usr/bin/tiff2pdf
COPY integration_tests/docker/mock_cmd.sh /usr/bin/mutt

COPY . /usr/src/wazo-agid

WORKDIR /usr/src/wazo-agid
RUN python setup.py develop
